[LUBM4OBDA]
#mappings=testing/gtfs_postgresql.r2rml.ttl
mappings=testing/lubm4obda.r2rml.ttl

# CONNECTOR-X URI
db_url=postgresql://root:root@localhost:5432/lubm4obda
#db_url=postgresql+psycopg://root:root@localhost:5432/gtfs
